### ISSUE TITLE
There is no file AuthData.java and we can't compile

### ISSUE THREAD

**Issue by tomekb530** [berkay2578/soapbox-race-launcher#1]
Like in title..

**Comment by berkay2578** [comment]
I never introduced or utilized something called `AuthData.java`, do you have the full trace log?

Edit: You're talking about `AuthType`, eclipse skipped it during my last commit. I'll upload the file now.

Edit 2: Fixed in 4809134

**Comment by tomekb530** [comment]
Sorry, my mistake about name :)
